# Generated by Django 3.2 on 2021-04-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210430_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date1',
        ),
    ]
